name: database
services:
  postgres:
    container_name: postgres
    image: postgres:15
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - database
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgsql-data:
    name: pgsql-data
    driver: local
networks:
  database:
    external: true