name: database
services:
  postgres:
    container_name: pgsql
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgsql-data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - database
volumes:
  pgsql-data:
    driver: local
networks:
  database:
    external: true