services:
  whoami:
    container_name: whoami
    hostname: "whoami"
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - web
    # Here we define our settings for traefik how to proxy our service.
    security_opt:
      - no-new-privileges:true
    labels:
      # This is enableing treafik to proxy this service
      - "traefik.enable=true"
      # Here we have to define the URL
      # More details https://doc.traefik.io/traefik/v2.0/routing/routers/#rule
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      # Here we define in wich network treafik can find this service
      - "traefik.docker.network=web"
      # This is the port that traefik should proxy
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # Activation of TLS
      - "traefik.http.routers.whoami.tls=true"

networks:
  web:
    external: true