name: database
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      timeout: 45s
      interval: 10s
      retries: 10
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web
      - database
    labels:
      # This is enableing treafik to proxy this service
      - "traefik.enable=true"
      # Here we have to define the URL
      # More details https://doc.traefik.io/traefik/v2.0/routing/routers/#rule
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.docker.localhost`)"
      # Here we define in wich network treafik can find this service
      - "traefik.docker.network=web"
      # This is the port that traefik should proxy
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      # Activation of TLS
      - "traefik.http.routers.phpmyadmin.tls=true"
volumes:
  mysql-data:
    driver: local

networks:
  web:
    external: true
  database:
    external: true